version: "3.0"
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "9306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fusebox
      MYSQL_DATABASE: fusebox
      MYSQL_USER: fusebox
      MYSQL_PASSWORD: fusebox
  fusebox:
    build: .
    working_dir: /app/fusebox/fusebox
    volumes:
      - .:/app
    depends_on:
      - mysql
    ports:
      - "9004:4000"
