version: "2.0"
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - webnet
  fusebox:
    image: titomiguelcosta/fusebox:latest
    build: .
    working_dir: /app/fusebox/fusebox
    volumes:
      - .:/app
    depends_on:
      - mysql
    ports:
      - "5000:4000"
    networks:
      - webnet
networks:
  webnet:
