version: "3.1"
services:
  fusebox-mysql:
    image: mysql:5.7
    container_name: fusebox-mysql
    restart: always
    volumes:
      - .:/app
      - ./database:/var/lib/mysql
    ports:
      - "9306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: fusebox
      MYSQL_USER: fusebox
      MYSQL_PASSWORD: 1234567
  fusebox-gunicorn:
    container_name: fusebox-gunicorn
    build: .
    working_dir: /app/fusebox
    volumes:
      - .:/app
    depends_on:
      - fusebox-mysql
    ports:
      - "9004:4000"

