version: "3.1"
services:
  fusebox-mysql:
    image: mysql:5.7
    container_name: fusebox-mysql
    restart: always
    volumes:
      - .:/app
      - ./database:/var/lib/mysql
    ports:
      - "9306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: fusebox
      MYSQL_USER: fusebox
      MYSQL_PASSWORD: 1234567
  fusebox-web:
    container_name: fusebox-web
    image: "node:12"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./web:/home/node/app
    stdin_open: true
    command: bash -c "yarn upgrade && yarn build && yarn start"
    ports:
      - "9003:3000"
  fusebox-api:
    container_name: fusebox-api
    build: .
    working_dir: /app/fusebox
    volumes:
      - .:/app
    depends_on:
      - fusebox-mysql
    ports:
      - "9004:4000"

