version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - ./fusebox/.env
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - webnet
  fusebox:
    image: titomiguelcosta/fusebox:latest
    build: .
    volumes:
      - .:/app
    env_file:
      - ./fusebox/.env
    depends_on:
      - mysql
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:4000"
    networks:
      - webnet
    command: ["./docker_boot.sh", "0.0.0.0:4000", "--chdir", "/app/fusebox/fusebox", "--reload", "wsgi:application"]
networks:
  webnet:
