# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='track',
            name='populated',
            field=models.BooleanField(default=False),
        ),
    ]
