# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
