# Generated by Django 3.1.2 on 2020-10-21 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlisttracks',
            options={'verbose_name_plural': 'Playlist tracks'},
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='youtube', max_length=255)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('video_id', models.CharField(max_length=255)),
                ('channel_id', models.CharField(blank=True, max_length=255)),
                ('published_on', models.DateTimeField(blank=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tracks_track', to='api.track')),
            ],
        ),
    ]
