# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171119_0556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='played',
            options={'verbose_name_plural': 'Played'},
        ),
    ]
